version: "3.5"

networks:
  app-net:
  test-net:

volumes:
  app-vol:

services:
  web-app:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000

    networks:
      - app-net

  client:
    container_name: client
    build:
      context: client/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net

  redis:
    image: "redis:alpine"
    networks:
      - app-net


#######################
#        TESTS        #
#######################
  test_db:
    image: "redis:alpine"
    networks:
      - test-net

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - target: 5003
        published: 5003
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      REDIS_HOST: test_db
      REDIS_PORT: 6379
      FLASK_HOST: 127.0.0.1
      FLASK_PORT: 5003
    networks:
      - test-net
    depends_on:
      - test_db
