FROM python:3.9-alpine

MAINTAINER Vadym Khodak

COPY app.py /src/app.py
COPY requirements.txt /src/requirements.txt
COPY tests /src/tests

WORKDIR /src

RUN pip install -r requirements.txt
RUN pip install pytest==6.2.4 requests==2.25.1

ENTRYPOINT ["pytest", "tests"]
