version: "3.5"
services:
  web-app:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-vol
        target: /src
  client:
    container_name: client
    build:
      context: client/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net
  redis:
    image: "redis:alpine"
    networks:
      - app-net

networks:
  app-net:

volumes:
  app-vol:
