version: "3.8"

networks:
  app-net:
  test-net:

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - target: 8000
        published: 8000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-net
    depends_on:
      - redis

  client:
    container_name: client
    build:
      context: client/
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net
    depends_on:
      - server

  redis:
    image: "redis:alpine"
    networks:
      - app-net


#######################
#        TESTS        #
#######################
  test_db:
    image: "redis:alpine"
    networks:
      - test-net

  test:
    build:
      context: server/
      dockerfile: Dockerfile.test
    ports:
      - target: 8001
        published: 8001
    environment:
      REDIS_HOST: test_db
      REDIS_PORT: 6379
    networks:
      - test-net
    depends_on:
      - test_db
