version: "3.5"
services:
  web-app:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000

    networks:
      - app-net
  redis:
    image: "redis:alpine"
    networks:
      - app-net

networks:
  app-net:

volumes:
  app-vol:
