version: "3.5"
services:
  web-app:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-vol
        target: /src
  redis:
    image: "redis:alpine"
    networks:
      - app-net

networks:
  app-net:

volumes:
  app-vol:
