version: "3.8"

networks:
  app-net:

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - target: 8000
        published: 8000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-net
    depends_on:
      - redis

  client:
    container_name: client
    build:
      context: client/
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net
    depends_on:
      - server

  redis:
    image: "redis:alpine"
    networks:
      - app-net


#######################
#        TESTS        #
#######################
  test_db:
    image: "redis:alpine"
    networks:
      - test-net

  test:
    build:
      context: .
      dockerfile: flask_server/Dockerfile.test
    ports:
      - target: 5003
        published: 5003
    environment:
      FLASK_SECRET_KEY: some-secret-key
      REDIS_HOST: test_db
      REDIS_PORT: 6379
      FLASK_HOST: 127.0.0.1
      FLASK_PORT: 5003
    networks:
      - test-net
    depends_on:
      - test_db
