version: "3.5"
services:
  web-app:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000

    networks:
      - app-net

  client:
    container_name: client
    build:
      context: client/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net

  redis:
    image: "redis:alpine"
    networks:
      - app-net

networks:
  app-net:

volumes:
  app-vol:
