apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 5
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: counter-pod
          image: vaddimart/playwithk8s:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: flasksecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
