apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: db-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: redis-be
