apiVersion: v1
kind: Service
metadata:
  name: be-svc
spec:
  selector:
    app: be-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: fe-svc
spec:
  selector:
    app: fe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: db-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: redis-be
