
FROM python:3.9-alpine

MAINTAINER Vadym Khodak

COPY main.py /app/main.py
COPY config.py /app/config.py
COPY tests /app/tests
COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install pytest==6.2.4 requests==2.25.1

ENTRYPOINT ["pytest", "tests"]